config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :line_items

  resources :carts

  resources :products

   root 'products#index'
   get 'login'=>"session#new", as: :login
   post 'login'=>"session#create"
   patch 'logout'=>"session#destroy", as: :logout

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles:{medium: "300x300>", thumb: "100x100>"}
  has_many :line_items, dependent: :nullify
  before_destroy :can_destroy?
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :name, presence: true, length: {maximum: 200}
  validates :weight, numericality: {only_integer: true, greater_than: 0}, allow_blank: true
  validates_attachment :image, content_type: {content_type: /\Aimage\//}
  def can_destroy?
    line_items.blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :manager_permission, only:[:new, :create, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Товар успешно создан.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Товар успешно отредактирован.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Товар успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :discription, :price, :weight, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.haml
= form_for @product do |f|
  =error_messages_for(@product)
  .row
    .col-md-3
      .form-group
        =f.label :name
        =f.text_field :name, class: "form-control"
    .col-md-3
      .from-group
        =f.label :discription
        =f.text_area :discription, class: "form-control"
    .col-md-3
      .from-group
        =f.label :price
        .input-group
          =f.text_field :price, class: "form-control"
          %span.input-group-addon руб
    .col-md-3
      .from-group
        =f.label :weight
        =f.text_field :weight, class: "form-control"
      .form-group
        =f.label :image
        =f.file_field :image, class: "form-control"

  .actions
    =f.submit nil, class: "btn btn-primary"

app/views/products/edit.html.haml
%h1 Редактирование товара

= render 'form'

= link_to 'Показать', @product
\|
= link_to 'Назад', products_path

app/views/products/index.html.haml
%h1 Список товаров

.row
  .list-group
    .col-md-9
      - @products.each do |product|
        =link_to product, :class => "list-group-item" do
          .list-group-item-text
            %p= product.name
          .list-group-item-text
            %p= product.discription
          .list-group-item-number
            %b= number_to_currency(product.price)
          .list-group-item-number
            %b= product.weight
          = link_to 'Показать', product, class:"btn btn-primary"
          = link_to 'Редактировать', edit_product_path(product), class:"btn btn-primary"
          = link_to 'Удалить', product, :method => :delete, :data => { :confirm => 'Вы уверены?' }, class:"btn btn-primary"

=paginate @products

%h4= link_to 'Новый товар', new_product_path, class:"btn btn-primary"

app/views/products/new.html.haml
%h1 Новый товар

= render 'form'

= link_to 'Назад', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Название:
  = @product.name
%p
  %b Описание:
  = @product.discription
%p
  %b Цена:
  = number_to_currency(@product.price)
%p
  %b Вес:
  = @product.weight

= link_to 'Редактировать', edit_product_path(@product)
\|
= link_to 'Назад', products_path
\|
-if @product.image?
  = link_to @product.image.url do
    =image_tag @product.image.url(:medium)
\|
= link_to line_items_path(product_id:@product.id), data:{method: :post, remote: :true}, class: "btn btn-primary" do
  =fa_icon "cart-plusrai"
  Добавить в корзину